/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gite;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;

/**
 *
 * @author ranasgalla.niccolo
 */
public class GraficaGite extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GraficaGite.class.getName());

    private GestioneFileStudenti gestStudenti;
    private GestioneFileGite     gestGite;
    /**
     * Creates new form GraficaGite
     */
    public GraficaGite() {
        initComponents();
        gestStudenti = new GestioneFileStudenti();
        gestGite     = new GestioneFileGite();
        caricaGiteNelComboBox();
    }
    
    private void caricaGiteNelComboBox() {
        Gita[] gite = gestGite.leggiTutteGite();
        cmbGiteDisponibili.removeAllItems();
        for (Gita g : gite) {
            cmbGiteDisponibili.addItem(g.getNome()); // mostra il nome, l'indice = id
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblCognome = new javax.swing.JLabel();
        lblClasse = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCognome = new javax.swing.JTextField();
        txtClasse = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cmbGiteDisponibili = new javax.swing.JComboBox<>();
        btnIscrivi = new javax.swing.JButton();
        btnLeggi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setText("Nome");

        lblCognome.setText("Cognome");

        lblClasse.setText("Classe");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        cmbGiteDisponibili.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnIscrivi.setText("Iscrivi");
        btnIscrivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIscriviActionPerformed(evt);
            }
        });

        btnLeggi.setText("Leggi File");
        btnLeggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeggiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCognome)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblClasse)
                                .addComponent(lblNome, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txtClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCognome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLeggi)
                            .addComponent(cmbGiteDisponibili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIscrivi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCognome)
                            .addComponent(txtCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClasse)
                            .addComponent(txtClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cmbGiteDisponibili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIscrivi)
                        .addGap(18, 18, 18)))
                .addComponent(btnLeggi)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnLeggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeggiActionPerformed
        jTextArea1.setText(""); // pulizia area testo

        Studente[] studenti   = gestStudenti.leggiTuttiStudenti();
        Gita[]     gite       = gestGite.leggiTutteGite();
        int[][]    iscrizioni = gestGite.leggiTutteIscrizioni();

        if (iscrizioni.length == 0) {
            jTextArea1.append("Nessuna iscrizione presente.\n");
            return;
        }

        jTextArea1.append("=== ISCRIZIONI ===\n");
        for (int[] isc : iscrizioni) {
            int idS = isc[0];
            int idG = isc[1];

            String nomeStudente    = (idS >= 0 && idS < studenti.length)
                    ? studenti[idS].getNome() + " " + studenti[idS].getCognome()
                    : "Studente #" + idS;
            String nomeGita        = (idG >= 0 && idG < gite.length)
                    ? gite[idG].getNome()
                    : "Gita #" + idG;

            jTextArea1.append("• " + nomeStudente + " [ID " + idS + "]"
                    + " → " + nomeGita + " [ID " + idG + "]\n");
        }
    }//GEN-LAST:event_btnLeggiActionPerformed

    private void btnIscriviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIscriviActionPerformed
       String nome    = txtNome.getText().trim();
        String cognome = txtCognome.getText().trim();
        String classe  = txtClasse.getText().trim();

        // Validazione campi
        if (nome.isEmpty() || cognome.isEmpty() || classe.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Compila tutti i campi (Nome, Cognome, Classe).",
                "Attenzione", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (cmbGiteDisponibili.getSelectedIndex() == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Seleziona una gita.",
                "Attenzione", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ID gita = indice selezionato nel combobox (corrisponde al record nel file)
        int idGita = cmbGiteDisponibili.getSelectedIndex();

        // Crea lo studente con id temporaneo -1 (verrà assegnato dal file)
        Studente s = new Studente(nome, cognome, classe, -1);

        // Salva lo studente nel file e recupera l'ID assegnato
        int idStudente = gestStudenti.aggiungiStudente(s);

        if (idStudente == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Errore nel salvataggio dello studente.",
                "Errore", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Salva l'iscrizione (idStudente, idGita) nel file iscrizioni
        gestGite.aggiungiIscrizione(idStudente, idGita);

        // Feedback all'utente
        jTextArea1.append("✓ " + nome + " " + cognome
                + " (ID " + idStudente + ") iscritto a: "
                + cmbGiteDisponibili.getSelectedItem()
                + " (ID " + idGita + ")\n");

        // Pulizia campi
        txtNome.setText("");
        txtCognome.setText("");
        txtClasse.setText("");
    }//GEN-LAST:event_btnIscriviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GraficaGite().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIscrivi;
    private javax.swing.JButton btnLeggi;
    private javax.swing.JComboBox<String> cmbGiteDisponibili;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblClasse;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtClasse;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
